// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaFIMuEruRWzxBeFuuoQXB8Mj_P_1GZ28',
    appId: '1:660740272526:web:d68802ef8ad32a0edaf4df',
    messagingSenderId: '660740272526',
    projectId: 'fir-authentication-e768d',
    authDomain: 'fir-authentication-e768d.firebaseapp.com',
    storageBucket: 'fir-authentication-e768d.firebasestorage.app',
    measurementId: 'G-YLLQ99JK9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPX_2RLEAfJYab-nET3_FQaiqyYYhMdtM',
    appId: '1:660740272526:android:0a32451cb27f93dfdaf4df',
    messagingSenderId: '660740272526',
    projectId: 'fir-authentication-e768d',
    storageBucket: 'fir-authentication-e768d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrkjLY41wvSTs82_Or_XRg3MiYoiErfQ',
    appId: '1:660740272526:ios:6e98035fca2d85eedaf4df',
    messagingSenderId: '660740272526',
    projectId: 'fir-authentication-e768d',
    storageBucket: 'fir-authentication-e768d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
